---
language: python
python: "2.7"

cache: pip

install:
  - pip install ansible ansible-lint yamllint

before_script:
  - find . -name '*.yml' -print0 | xargs -n1 -0 yamllint -c .yamllint.yml
  - ansible-lint site.yml

script:
  - ansible-playbook --syntax-check -i inventories/localhost site.yml
  - ansible-playbook --list-hosts -i inventories/localhost site.yml
  - ansible-playbook --list-tags -i inventories/localhost site.yml
  - ansible-playbook --list-tasks -i inventories/localhost site.yml

notifications:
  email: false
