---
- name: Common role for all hosts
  hosts: all
  become: true
  tags: ['common']
  roles:
    - role: common

- name: Install and configure znc
  hosts: znc
  become: true
  tags: ['znc']
  roles:
    - znc
