---
- name: Common role for all hosts
  hosts: all
  become: true
  tags: ['common']
  roles:
    - role: common

- name: Install and configure znc
  hosts: znc
  become: true
  tags: ['znc']
  roles:
    - znc

- name: NGINX role for NGINX hosts
  hosts: nginx
  become: true
  tags: ['nginx']
  roles:
    - role: nginx
