---
extra_packages:
  - vim
  - zsh

system_users:
  - eggshell:
    name: eggshell
    groups: sudo
    shell: /usr/bin/zsh
  - matthew:
    name: matthew
    groups: sudo
    shell: /usr/bin/zsh

znc_users:
  - foo:
    name: foo
    password: "ch@ng3me"
    nick: foo
    ident: foo
    realname: "Dr. Foo Bar"
    admin: true
